version: 0.2

phases:
  build:
    commands:
       - mvn clean install
  post_build:
    commands:
      - mvn package
artifacts:
  files:
    - '**/*'
  base-directory: 'target/Sample'
